# Generated by Django 3.1.4 on 2020-12-28 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('lang', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Каналы',
                'db_table': 'channels',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=40)),
                ('token', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Сервис',
                'db_table': 'token',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(db_index=True, max_length=21)),
                ('stop', models.CharField(max_length=21)),
                ('title', models.TextField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('date_start', models.DateField()),
                ('date_stop', models.DateField()),
                ('begin', models.IntegerField()),
                ('end', models.IntegerField()),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.channelmodel')),
            ],
            options={
                'verbose_name_plural': 'Программы',
                'db_table': 'programmes',
                'ordering': ['channel_id'],
            },
        ),
        migrations.CreateModel(
            name='ChannelTokenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1)),
                ('date_select', models.IntegerField(blank=True, editable=False)),
                ('channel', models.ManyToManyField(to='app.ChannelModel')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tokenmodel')),
            ],
            options={
                'verbose_name_plural': 'Сервис - Каналы',
                'db_table': 'channel_token',
                'ordering': ('token',),
            },
        ),
    ]
